const data = {
  users: [
    {
      name: 'dawa',
      email: 'dawa@gmail.com',
      // password: bcrypt.hashSync('dawadawa'),
      password: 'dawa',
      isAdmin: true,
    },
    {
      name: 'sherpa',
      email: 'sherpa@gmail.com',
      // password: bcrypt.hashSycn('sherpa'),
      password: 'sherpa',
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Hight quality shirt',
    },

    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'Hight quality product',
    },

    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 14,
      description: 'Hight quality product',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Adidas',
      rating: 3,
      numReviews: 14,
      description: 'Hight quality product',
    },
  ],
};

export default data;
